name: Deploy my site to Pages

on:
  push:
    branches: ["main"]  # Set this to your default branch if it's not 'main'
  workflow_dispatch:    # Allows you to run the workflow manually

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent multiple deployments from running at the same time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just building
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the repository's root directory
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
